// Builds src/styles/tokens.css from scripts/tokens.config.mjs and checks contrast.
// Usage: npm run tokens
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { H, BASE, RECIPE, CATS, THEMES, CHECKS } from './tokens.config.mjs';

/* ---------- OKLCH → sRGB with chroma reduction to stay in gamut ---------- */
function okLin(L, C, h) {
  const a = C * Math.cos((h * Math.PI) / 180), b = C * Math.sin((h * Math.PI) / 180);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s
  ];
}
const inGamut = (c) => c.every((v) => v >= -1e-4 && v <= 1 + 1e-4);
const toS = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);
const toLin = (x) => (x <= 0.04045 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4);
function rgb(L, C, h) {
  let c = okLin(L, C, h);
  if (!inGamut(c)) {
    let lo = 0, hi = C;
    for (let i = 0; i < 24; i++) { const mid = (lo + hi) / 2; if (inGamut(okLin(L, mid, h))) lo = mid; else hi = mid; }
    c = okLin(L, lo, h);
  }
  return c.map((v) => Math.round(Math.min(1, Math.max(0, toS(Math.min(1, Math.max(0, v))))) * 255));
}
const hex = (c) => '#' + c.map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase();
const lum = (c) => { const [r, g, b] = c.map((v) => toLin(v / 255)); return 0.2126 * r + 0.7152 * g + 0.0722 * b; };
const ratio = (a, b) => { const x = lum(a), y = lum(b); return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05); };

/* ---------- resolve every role for one mode ---------- */
function roles(mode) {
  const out = {};
  for (const [k, [L, C, d, abs]] of Object.entries(BASE[mode])) out[k] = { rgb: rgb(L, C, abs ? d : H + d), src: [L, C, abs ? d : H + d] };
  const r = RECIPE[mode];
  for (const [c, { hues: [hd, hm, hp] }] of [...Object.entries(CATS), ...Object.entries(THEMES)]) {
    out[c] = { rgb: rgb(...r.d, hd), src: [...r.d, hd] };
    out[`${c}-m`] = { rgb: rgb(...r.m, hm), src: [...r.m, hm] };
    out[`${c}-p`] = { rgb: rgb(...r.p, hp), src: [...r.p, hp] };
    out[`${c}-s`] = { rgb: rgb(...r.s, hd), src: [...r.s, hd] };
  }
  return out;
}
const R = { light: roles('light'), dark: roles('dark') };

/* ---------- contrast gate ---------- */
let failed = 0;
const report = [];
for (const mode of ['light', 'dark']) {
  for (const [fg, bg, min] of CHECKS) {
    const v = ratio(R[mode][fg].rgb, R[mode][bg].rgb);
    const ok = v >= min;
    if (!ok) failed++;
    report.push(`${ok ? ' ok ' : 'FAIL'}  ${mode.padEnd(5)} ${fg.padEnd(8)} on ${bg.padEnd(8)} ${v.toFixed(2)} (min ${min})`);
  }
}

/* ---------- CSS ---------- */
const block = (mode) => Object.entries(R[mode]).map(([k, v]) => `--${k}:${hex(v.rgb)};`).join(' ');
const ctx = [...Object.keys(CATS), ...Object.keys(THEMES)]
  .map((c) => `[data-cat="${c}"]{--ctx:var(--${c});--ctxm:var(--${c}-m);--ctxp:var(--${c}-p);--ctxs:var(--${c}-s);--dot:var(--${c}-s)}`)
  .join('\n');
const css = `/* GENERATED by scripts/gen-tokens.mjs from scripts/tokens.config.mjs — do not edit by hand. Identity hue H = ${H}. */
:root{color-scheme:light; ${block('light')}
  /* context: outside any work the page speaks in identity blue */
  --ctx:var(--band);--ctxm:var(--band-m);--ctxp:var(--wash);--ctxs:var(--acc);--dot:var(--spark);
  --sh-o:.22;--edge:color-mix(in srgb,var(--shade) 55%,transparent);--cloud-a:.46;--cloud-b:.22;--tint-a:.34;
  /* isometric objects (IsoObject): lit from above in both modes — top brightest, left mid, right darkest */
  --iso-nt:var(--surface);--iso-nl:var(--sunk);--iso-nr:color-mix(in oklab,var(--sunk),var(--shade) 22%);--iso-hi:var(--surface);--iso-kt:var(--chip);--iso-kl:color-mix(in oklab,var(--chip),#000 25%);--iso-kr:color-mix(in oklab,var(--chip),#000 45%);--iso-edge:var(--edge);--iso-s1:30%;--iso-s2:50%;--iso-cb:0%;--obj-col:color-mix(in srgb,var(--ink) 78%,var(--bg));}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){color-scheme:dark; ${block('dark')}
  --sh-o:.6;--edge:color-mix(in srgb,var(--ink) 20%,transparent);--cloud-a:.12;--cloud-b:.44;--tint-a:.68;
  --iso-nt:color-mix(in oklab,var(--ink) 40%,var(--bg));--iso-nl:color-mix(in oklab,var(--ink) 27%,var(--bg));--iso-nr:color-mix(in oklab,var(--ink) 17%,var(--bg));--iso-hi:color-mix(in oklab,var(--ink) 70%,var(--bg));--iso-kt:color-mix(in oklab,var(--ink) 20%,var(--bg));--iso-kl:color-mix(in oklab,var(--ink) 13%,var(--bg));--iso-kr:color-mix(in oklab,var(--ink) 8%,var(--bg));--iso-edge:color-mix(in srgb,var(--shade) 70%,transparent);--iso-s1:16%;--iso-s2:30%;--iso-cb:48%;--obj-col:color-mix(in oklab,var(--bg),#000 30%);}}
:root[data-theme="dark"]{color-scheme:dark; ${block('dark')}
  --sh-o:.6;--edge:color-mix(in srgb,var(--ink) 20%,transparent);--cloud-a:.12;--cloud-b:.44;--tint-a:.68;
  --iso-nt:color-mix(in oklab,var(--ink) 40%,var(--bg));--iso-nl:color-mix(in oklab,var(--ink) 27%,var(--bg));--iso-nr:color-mix(in oklab,var(--ink) 17%,var(--bg));--iso-hi:color-mix(in oklab,var(--ink) 70%,var(--bg));--iso-kt:color-mix(in oklab,var(--ink) 20%,var(--bg));--iso-kl:color-mix(in oklab,var(--ink) 13%,var(--bg));--iso-kr:color-mix(in oklab,var(--ink) 8%,var(--bg));--iso-edge:color-mix(in srgb,var(--shade) 70%,transparent);--iso-s1:16%;--iso-s2:30%;--iso-cb:48%;--obj-col:color-mix(in oklab,var(--bg),#000 30%);}
/* .tone-light: a subtree that keeps the light palette in dark mode too (the object column in a LabItem card: the
   object and its charcoal backdrop look the same in both modes — no inverted object). Put data-cat on the same element. */
.tone-light{color-scheme:light; ${block('light')}
  --ctx:var(--band);--ctxm:var(--band-m);--ctxp:var(--wash);--ctxs:var(--acc);--dot:var(--spark);
  --sh-o:.22;--edge:color-mix(in srgb,var(--shade) 55%,transparent);--sel-k:78%;
  --iso-nt:var(--surface);--iso-nl:var(--sunk);--iso-nr:color-mix(in oklab,var(--sunk),var(--shade) 22%);--iso-hi:var(--surface);--iso-kt:var(--chip);--iso-kl:color-mix(in oklab,var(--chip),#000 25%);--iso-kr:color-mix(in oklab,var(--chip),#000 45%);--iso-edge:var(--edge);--iso-s1:30%;--iso-s2:50%;--iso-cb:0%;--obj-col:color-mix(in srgb,var(--ink) 78%,var(--bg));}
/* .tone-dark: the dark palette on one element in light mode — the theme-switch plane (scripts/theme.ts) paints the
   ground of the mode it is switching to (.tone-light does the same the other way) */
.tone-dark{color-scheme:dark; ${block('dark')}}
/* context: inside a work's area every color comes from its kind (spec 8.4.1) */
[data-cat="self"]{--ctx:var(--band);--ctxm:var(--band-m);--ctxp:var(--wash);--ctxs:var(--acc);--dot:var(--spark)}
${ctx}
`;
const out = fileURLToPath(new URL('../src/styles/tokens.css', import.meta.url));
writeFileSync(out, css);

// machine-readable copy for the kit page and docs
const json = { H, modes: Object.fromEntries(['light', 'dark'].map((m) => [m, Object.fromEntries(Object.entries(R[m]).map(([k, v]) => [k, { hex: hex(v.rgb), oklch: v.src }]))])), cats: CATS, themes: THEMES, checks: report };
writeFileSync(fileURLToPath(new URL('../src/lib/tokens.json', import.meta.url)), JSON.stringify(json, null, 1));

console.log(report.join('\n'));
console.log(`\nwrote src/styles/tokens.css (${Object.keys(R.light).length} roles × 2 modes) · ${failed ? failed + ' contrast FAIL' : 'all contrast checks pass'}`);
if (failed) process.exit(1);
