// Generates docs/COMPONENTS.md and docs/components.json from the doc header + Props of every component.
// The component file is the single source of truth — edit its header, then run `npm run docs`.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseDoc, GROUPS } from './docparse.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const walk = (d) => readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(d, e.name)) : e.name.endsWith('.astro') ? [join(d, e.name)] : []));
const files = walk(join(root, 'src/components')).filter((f) => !f.includes(`${sep}kit${sep}`));
const docs = files.map((f) => parseDoc(readFileSync(f, 'utf8'), relative(root, f))).filter(Boolean);
const missing = files.filter((f) => !docs.find((d) => d.file === relative(root, f)));

const esc = (s = '') => s.replace(/\|/g, '\\|');
let md = `# Components

> Generated by \`npm run docs\` from the header of each file in \`src/components/\`. Do not edit by hand — edit the component.
> Live specimens: \`/kit/\` (and \`/th/kit/\`, \`/ja/kit/\`). How to compose them: \`docs/STORY-RECIPES.md\`. Rules: \`docs/DESIGN-RULES.md\`.

**Localized text** (\`L\`): a plain string, or \`{ en, th?, ja? }\`. Missing languages fall back to English.
**Media keys**: \`"<work-id>/<file>"\` → \`src/assets/works/<work-id>/<file>\`. A missing file fails the build.
**Context color**: components inside an element with \`data-cat="<kind>"\` take that kind's colors; everything else is identity blue.

`;
md += '## Index\n\n' + GROUPS.map((g) => `- **${g.title}** — ${docs.filter((d) => d.group === g.key).map((d) => `[${d.name}](#${d.name.toLowerCase()})`).join(', ')}`).join('\n') + '\n';
for (const g of GROUPS) {
  const list = docs.filter((d) => d.group === g.key).sort((a, b) => a.name.localeCompare(b.name));
  if (!list.length) continue;
  md += `\n---\n\n## ${g.title}\n\n${g.note}\n`;
  for (const d of list) {
    md += `\n### ${d.name}\n\n\`${d.file}\`\n\n${d.summary ?? ''}\n\n`;
    if (d.use) md += `- **Use:** ${d.use}\n`;
    if (d.avoid) md += `- **Avoid:** ${d.avoid}\n`;
    if (d.behavior) md += `- **Behavior:** ${d.behavior}\n`;
    if (d.states) md += `- **States:** ${d.states}\n`;
    if (d['props-note']) md += `- **Note:** ${d['props-note']}\n`;
    if (d.props.length) {
      md += `\n| prop | type | notes |\n|---|---|---|\n`;
      for (const p of d.props) md += `| \`${p.name}\`${p.optional ? '' : ' **(required)**'} | \`${esc(p.type)}\` | ${esc(p.doc)} |\n`;
    }
    if (d.example) md += `\n\`\`\`astro\n${d.example}\n\`\`\`\n`;
  }
}
writeFileSync(join(root, 'docs/COMPONENTS.md'), md);
writeFileSync(join(root, 'docs/components.json'), JSON.stringify(docs, null, 1));
console.log(`docs: ${docs.length} components → docs/COMPONENTS.md, docs/components.json`);
if (missing.length) { console.error('missing doc header:\n  ' + missing.join('\n  ')); process.exit(1); }
